### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by jbcpollak** [Khan/pull-request-comment-trigger#22]
in the last hour we have started getting the following errors, is it possible the `dist/index.js` is broken?

```
Run khan/pull-request-comment-trigger@master
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.880 (/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:137:33)
    at __webpack_require__ (/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:25:31)
    at Object.62 (/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:57:14)
    at __webpack_require__ (/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:25:31)
    at startup (/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:44:19)
    at /home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js:48:18 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/khan/pull-request-comment-trigger/master/dist/index.js'
  ]
}
```

cc/ @ajeisens

**Comment by lukeredpath** [comment]
Same here. This has just broken some of our pipelines. Is it possible to pin a third party GitHub action to a specific commit?

**Comment by YusufGandhi** [comment]
Same here. This has broken all our pipelines.

**Comment by wimoMisterX** [comment]
@lukeredpath yep I've pinned it `khan/pull-request-comment-trigger@ca8f46e213c14a9c38231cb031f66e16df796fe0`

**Comment by jdrphillips** [comment]
I'm having trouble with the commit `ca8f46e213c14a9c38231cb031f66e16df796fe0` - it seemingly randomly ignores some PR comments

**Comment by jbcpollak** [comment]
@jaredly - not sure if you get pinged on issues automatically but since you made the commits yesterday, any chance you could take a look soon?

**Comment by jaredly** [comment]
Fixed! sorry about that

**Comment by jbcpollak** [comment]
confirmed this does seem to solve the problem, we used `khan/pull-request-comment-trigger@v1.1.0`

Thanks!
